spring:
  config:
    activate:
      on-profile: performanceTest
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: OFF  # 전체 로그 끔
    org.hibernate: OFF  # Hibernate 전체 끔
    org.hibernate.SQL: OFF  # SQL 로그 끔
    org.hibernate.type.descriptor.sql.BasicBinder: OFF  # 바인딩 로그 끔
    org.springframework: OFF  # 스프링 로그도 완전히 끔